version: "3"
services:
    server:
        build: .
        container_name: "logs-viewer"
        working_dir: /var/www
        volumes:
            - ./:/var/www:delegated
        ports:
            - "80:80"
